let input = {"id": 2648554897564,
"email": "example@email.com",
"closed_at": null,
"created_at": "2020-08-21T11:45:56-04:00",
"updated_at": "2020-08-21T11:46:06-04:00",
"number": 252,
"note": null,
"gateway": "shopify_payments",
"test": false,
"total_price": "210.32",
"subtotal_price": "199.30",
"total_weight": 0,
"total_tax": "1.27",
"taxes_included": false,
"currency": "CAD",
"financial_status": "paid",
"confirmed": true,
"total_discounts": "0.00",
"total_line_items_price": "199.30",
"buyer_accepts_marketing": false,
"name": "#1252",
"referring_site": "",
"landing_site": "/account",
"cancelled_at": null,
"cancel_reason": null,
"total_price_usd": "159.66",
"reference": null,
"user_id": null,
"location_id": null,
"source_identifier": null,
"source_url": null,
"processed_at": "2020-08-21T11:45:54-04:00",
"device_id": null,
"phone": null,
"customer_locale": "en",
"landing_site_ref": null,
"order_number": 1252,
"discount_applications": [],
"discount_codes": [],
"line_items": [
  {"id": 5852747825308,
   "variant_id": 35086978089116,
   "title": "CHICKEN LEG",
   "quantity": 4,
   "sku": "1405",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399344087196,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "CHICKEN LEG",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 4,
   "grams": 0,
   "price": "2.81",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "2.81", "currency_code": "CAD"}, "presentment_money": {"amount": "2.81", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852747890844,
   "variant_id": 35086984872092,
   "title": "CHICKEN THIGHS, BONE IN, SKIN ON",
   "quantity": 12,
   "sku": "1430",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399347986588,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "CHICKEN THIGHS, BONE IN, SKIN ON",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 12,
   "grams": 0,
   "price": "1.56",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "1.56", "currency_code": "CAD"}, "presentment_money": {"amount": "1.56", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852747956380,
   "variant_id": 35086978056348,
   "title": "HERITAGE PORK CENTER CUT CHOPS",
   "quantity": 3,
   "sku": "2118",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399344054428,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "HERITAGE PORK CENTER CUT CHOPS",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 3,
   "grams": 0,
   "price": "5.00",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "5.00", "currency_code": "CAD"}, "presentment_money": {"amount": "5.00", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852747989148,
   "variant_id": 35086979137692,
   "title": "NATURALLY CURED BACON",
   "quantity": 1,
   "sku": "3108",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399345103004,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "NATURALLY CURED BACON",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 1,
   "grams": 0,
   "price": "10.49",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "10.49", "currency_code": "CAD"}, "presentment_money": {"amount": "10.49", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852748021916,
   "variant_id": 35086969372828,
   "title": "GROUND BEEF",
   "quantity": 2,
   "sku": "1102",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399341629596,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "GROUND BEEF",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 2,
   "grams": 0,
   "price": "8.19",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "8.19", "currency_code": "CAD"}, "presentment_money": {"amount": "8.19", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852748054684,
   "variant_id": 35086978678940,
   "title": "FLAX FED CHICKENS",
   "quantity": 1,
   "sku": "2413",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399344644252,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "FLAX FED CHICKENS",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 1,
   "grams": 0,
   "price": "23.96",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "23.96", "currency_code": "CAD"}, "presentment_money": {"amount": "23.96", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852748120220,
   "variant_id": 35086978252956,
   "title": "CHICKEN WINGS",
   "quantity": 3,
   "sku": "1407",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399344251036,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "CHICKEN WINGS",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 3,
   "grams": 0,
   "price": "6.29",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "6.29", "currency_code": "CAD"}, "presentment_money": {"amount": "6.29", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852748185756,
   "variant_id": 35086984675484,
   "title": "CHICKEN LEEK AND BACON PIE",
   "quantity": 1,
   "sku": "5165",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399347789980,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "CHICKEN LEEK AND BACON PIE",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 1,
   "grams": 0,
   "price": "28.00",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "28.00", "currency_code": "CAD"}, "presentment_money": {"amount": "28.00", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852748251292,
   "variant_id": 35086985035932,
   "title": "BEEF BURGERS",
   "quantity": 2,
   "sku": "1159",
   "variant_title": "",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399348150428,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "BEEF BURGERS",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 2,
   "grams": 0,
   "price": "13.32",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "13.32", "currency_code": "CAD"}, "presentment_money": {"amount": "13.32", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 },
 {"id": 5852748284060,
   "variant_id": 35087635775644,
   "title": "Refundable Credit Card Hold For Overweight Products",
   "quantity": 1,
   "sku": "",
   "variant_title": "Unit",
   "vendor": "TEST",
   "fulfillment_service": "manual",
   "product_id": 5399475290268,
   "requires_shipping": true,
   "taxable": false,
   "gift_card": false,
   "name": "Refundable Credit Card Hold For Overweight Products - Unit",
   "variant_inventory_management": null,
   "properties": [],
   "product_exists": true,
   "fulfillable_quantity": 1,
   "grams": 0,
   "price": "30.00",
   "total_discount": "0.00",
   "fulfillment_status": null,
   "price_set": {"shop_money": {"amount": "30.00", "currency_code": "CAD"}, "presentment_money": {"amount": "30.00", "currency_code": "CAD"}},
   "total_discount_set":
   {"shop_money": {"amount": "0.00", "currency_code": "CAD"}, "presentment_money": {"amount": "0.00", "currency_code": "CAD"}},
   "discount_allocations": [],
   "duties": []
 }
 ]
}

export default input;